register admin - wip, getting 403

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -4,11 +4,20 @@
 domain=$1
 path=$2
 is_public=$3
+admin=$4
+password=$5
 
 # Check domain/path availability
 sudo yunohost app checkurl $domain$path -a ghostblog
 if [[ ! $? -eq 0 ]]; then
-  exit 1
+    exit 1
+fi
+
+# Check that admin user is an existing account
+sudo yunohost user list | python ../conf/user_list.py | grep "^$admin$" >/dev/null
+if [[ ! $? -eq 0 ]]; then
+    echo "Error : the chosen admin user does not exist"
+    exit 1
 fi
 
 echo "Install dependencies..."
@@ -74,10 +83,19 @@ sudo update-rc.d ynh-ghostblog defaults
 sudo service ynh-ghostblog start
 sudo yunohost app service ynh-ghostblog -l $logfile
 
+echo "Setting up logrotate configuration..."
 sed -i "s@YNH_LOGFILE@$logfile@g" ../conf/logrotate
 sudo cp ../conf/logrotate /etc/logrotate.d/ynh-ghostblog
 
-echo "Reloading Nginx..."
+echo "Registering admin..."
+admin_name=$(sudo yunohost user list | python ../conf/user_getname.py $admin)
+admin_mail=$(sudo yunohost user list | python ../conf/user_getmail.py $admin)
+curl -kL -X POST https://$domain$path/ghost/signup --data-url-encode "name=$admin_name&email=$admin_mail&password=$password" > /dev/null 2>&1
+sudo yunohost app setting ghostblog admin -v $admin
+sudo yunohost app setting ghostblog password -v $password
 
+echo "Reloading Nginx..."
 sudo service nginx reload
 sudo yunohost app ssowatconf
+
+echo "Success ! You can go to https://$domain$path/ghost to write your posts"
